application: celestialbeadgcf
version: 0-0-2
runtime: go
api_version: go1

handlers:

- url: /images/favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /images/transpolaris\.png
  static_files: static/images/transpolaris.png
  upload: static/images/transpolaris\.png

- url: /styles/main\.css
  static_files: static/styles/main.css
  upload: static/styles/main\.css

- url: /scripts/draco\.js
  static_files: static/scripts/draco.js
  upload: static/scripts/draco\.js

- url: /.*
  script: _go_app

